name: Bug Report
description: File a bug report
labels: ["A: Bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      # NOTE: Prerequisites
      description: |
        To avoid invalid reports, please check and confirm following checkboxes.
      options:
        - label: This site DOES NOT contains sexually explicit material;
          required: true
        - label: The problem occurs only when using AdGaurd DNS or DNS filtering with AdGuard DNS filter, it does not depend on other ad blockers;
          required: true
        - label: AdGuard DNS filter was updated before redroduced an issue (ex. AdGuard Home);
          required: false
        - label: Browser version is up-to-date;
          required: false
        - label: If the site or app is broken, disabling AdGuard DNS resolves an issue.
          required: true

  - type: dropdown
    id: adguard-dns
    # NOTE: what adguard dns product
    attributes:
      label: What DNS server do you use?
      description: |
        If used third-party product, select Other and add its name in the comment field below.
      multiple: true
      options:
        - AdGuard public DNS
        - AdGuard private DNS
        - AdGuard Home
        - Other
    validations:
      required: true
