name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["A: Bug", "A: By Design", "A: Cannot reproduce", "A: Closed", "A: In progress", "A: Invalid", "A: Problematic", "A: Rejected", "A: Resolved", "A: Won't fix", "Extra", "Extra (zmc)", "Infrastructure", "N: AdGuard Browser Extension", "N: AdGuard Content Blocker", "N: AdGuard DNS", "N: AdGuard for Android", "N: AdGuard for iOS", "N: AdGuard for Mac", "N: AdGuard for Safari", "N: AdGuard for Windows", "N: Other", "NSFW", "P1: Critical", "P2: High", "P3: Medium", "P4: Low", "T: Ads", "T: Annoyance", "T: Anti Adblock Script", "T: Incorrect Blocking", "T: Popups", "T: Social Widget", "T: Stealth Mode issue", "T: Tracker"]
body:
  - type: dropdown
    id: adguards
    attributes:
      label: What product do you use?
      multiple: true
      options:
        - AdGuard Browser Extension
        - AdGuard Content Blocker
        - AdGuard DNS
        - AdGuard for Android
        - AdGuard for iOS
        - AdGuard for Mac
        - AdGuard for Safari
        - AdGuard for Windows
        - Other ad blocker
  - type: input
    id: version
    attributes:
      label: AdGuard version
      description: What version of our software are you running?
      placeholder: ex. 7.7
    validations:
      required: true
  - type: dropdown
    id: what-happened
    attributes:
      label: What type of problem have you encountered?
      multiple: true
      options:
        - Missed ads or ad leftovers
        - Website or app doesn't work properly with enabled AdGuard
        - AdGuard gets detected on a website
        - Social media buttons — share, like, tweet, etc.
        - Annoyances — pop-ups, cookie warnings, other notifications
        - Missed analytics or tracker;
        - Dangerous site
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true