name: Bug Report
description: File a bug report
labels: ["A: Bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      # NOTE: Prerequisites
      description: |
        To avoid invalid reports, please check and confirm following checkboxes.
      options:
        - label: This site DOES NOT contains sexually explicit material;
          required: true
        - label: The problem occurs only when using AdGaurd DNS or DNS filtering with AdGuard DNS filter, it does not depend on other ad blockers;
          required: true
        - label: AdGuard DNS filter was updated before redroduced an issue (ex. AdGuard Home);
          required: false
        - label: Browser version is up-to-date;
          required: false
        - label: If the site or app is broken, disabling AdGuard DNS resolves an issue.
          required: true

  - type: dropdown
    id: adguard-dns
    # NOTE: what adguard dns product
    attributes:
      label: What DNS server do you use?
      description: |
        If used third-party product, select Other and add its name in the comment field below.
      multiple: true
      options:
        - AdGuard public DNS
        - AdGuard private DNS
        - AdGuard Home
        - Other
    validations:
      required: true

  - type: input
    id: version
    # NOTE: ag server version
    attributes:
      label: AdGuard or other DNS server version
      description: What version of software are you running?
      placeholder: |
        ex. AdGuard Home v0.108.0-a.273+782de99a
    validations:
      required: false

  - type: textarea
    id: dns-upstreams
    # NOTE: upstreams
    attributes:
      label: What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?
      description: |
        If you're using AdGuard application or AdGuard Home with a custom DNS server, please provide the list of DNS upstreams that you have configured there.
      placeholder: |
        * ex. tls://unfiltered.adguard-dns.com - AdGuard non-filtered DNS over TLS
    validations:
      required: false

  - type: textarea
    id: filters
    # NOTE: dns filters
    attributes:
      label: What DNS filters do you have enabled?
      description: Give a list of enabled DNS filters in the field below if any are used.
      placeholder: |
        * ex. AdGuard DNS filter
        * ex. https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    validations:
      required: true

  - type: dropdown
    id: what-happened
    # NOTE: what happened
    attributes:
      label: What type of problem have you encountered?
      description: If the problem does not fall under any category that is listed here, please contact our tech support - support@adguard.com
      multiple: true
      options:
        - Missed ads
        - Missed analytics or tracker
        - Website or app doesn't work properly
    validations:
      required: true

  - type: dropdown
    id: browsers
    # NOTE: browser
    attributes:
      label: What browser is used?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Yandex Browser
        - Other (specify in comment below)
        - A problem is with an app or a device
    validations:
      required: true

  - type: dropdown
    id: device_type
    # NOTE: browser type
    attributes:
      label: Which device type is used?
      multiple: false
      options:
        - Desktop
        - Mobile
        - Other device
    validations:
      required: true

  - type: input
    id: url
    # NOTE: url of problem
    attributes:
      label: Where did you encounter the problem?
      description: |
        Please enter the page address or a download link of the affected app.
        If the problem with other device, please write a comment below
      placeholder: ex. https://example.com/
    validations:
      required: false

  - type: textarea
    id: comments
    # NOTE: comment
    attributes:
      label: Add your comment and screenshots
      description: |
        1. Please add screenshots of the problem. You can attach images by clicking this area to highlight it and then dragging files in or paste images from clipboard;
           Use `<details> </details>` tag to hide screenshots under the spoiler; 
        2. Please describe the issue extensively unless it is absolutely clear from the screenshot what the problem is;
        You can also indicate any other information that you think the developers should know.

        Warning: Please remove private info before upload screenshots!
      placeholder: |
        1. Your comment
        2. Screenshots
        <details> 
        
        paste screenshot here
        
        </details>
        
        <details>
        
        paste screenshot here
        
        </details>
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy
      description: By submitting this issue, you agree that report does not contain private info
      options:
        - label: I agree to follow this condition
          required: true
          